const investments=[
['Reserva de emergência','shield','#69B89B','Poupança','Baixo risco e alta liquidez para sua reserva de emergência ou oportunidade.'],
['Reserva de emergência','shield','#69B89B','Tesouro Selic e títulos CDI','Segurança, liquidez diária e rentabilidade atrelada aos juros.'],
['Prefixados','calendar','#7C8EE5','Tesouro ou CDBs Prefixados','Taxa definida na aplicação, ideal para cenários de queda da inflação.'],
['Prefixados','calendar','#7C8EE5','Debêntures e Letras Financeiras','Crédito privado com potencial de maior retorno e risco.'],
['Títulos híbridos · IPCA','trend','#EEA861','Tesouro IPCA+ ou CDBs IPCA+','Proteção do poder de compra com retorno acima da inflação.'],
['Títulos híbridos · IPCA','trend','#EEA861','Debêntures e Letras Financeiras IPCA','Crédito privado indexado à inflação, sem cobertura do FGC.'],
['Renda variável','spark','#D97891','ETFs, dividendos, FIIs e fundos','Renda periódica e valorização patrimonial no longo prazo.'],
['Renda variável','spark','#D97891','Ações de crescimento e cripto','Maior potencial de valorização, volatilidade e risco.'],
['Renda variável','spark','#D97891','Mercado futuro','Derivativos para proteção, especulação ou alavancagem.']];
const state={goal:Number(localStorage.getItem('xfinance-goal')||localStorage.getItem('lumina-goal'))||0,values:JSON.parse(localStorage.getItem('xfinance-values')||localStorage.getItem('lumina-values')||'{}')};
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v);
const parseMoney=v=>Number(v.replace(/\D/g,''))/100;
const icons={mark:'<svg viewBox="0 0 36 36"><path d="M10 27V15.5C10 10.8 13.7 7 18.3 7S27 10.8 27 15.5V27"/><path d="M15 27V16.3c0-1.8 1.4-3.3 3.2-3.3s3.3 1.5 3.3 3.3V27"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3 5 6v5c0 4.5 2.9 8.2 7 10 4.1-1.8 7-5.5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-5"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4m8-4v4M4 10h16"/></svg>',trend:'<svg viewBox="0 0 24 24"><path d="M4 18 10 12l4 4 6-9"/><path d="M15 7h5v5"/></svg>',spark:'<svg viewBox="0 0 24 24"><path d="m12 3 1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3Z"/></svg>'};
function header(step=1){return `<header><a class="brand" href="#">${icons.mark}<span><b>xfinance</b><small>investimento com propósito e pertencimento</small></span></a><div class="steps"><span class="step active">1</span><i></i><span class="step ${step>1?'active':''}">2</span><b>${step===1?'Seu objetivo':'Sua carteira'}</b></div><button class="avatar" aria-label="Perfil">MA</button></header>`}
function goalPage(){document.querySelector('#app').innerHTML=`${header()}<main class="goal-page"><section class="goal-copy"><span class="eyebrow">SEU FUTURO COMEÇA AQUI</span><h1>Quanto você quer<br><em>conquistar?</em></h1><p>Defina seu objetivo financeiro e dê o primeiro passo para transformar seus planos em realidade.</p><div class="assurance"><span>✓</span><div><b>Você está no controle</b><small>Seu objetivo pode ser ajustado quando quiser.</small></div></div></section><section class="goal-card"><div class="target-icon">◎</div><h2>Defina seu objetivo</h2><p>Qual valor você deseja alcançar?</p><label>VALOR DO OBJETIVO</label><div class="money-input"><span>R$</span><input id="goal" inputmode="numeric" placeholder="100.000,00" value="${state.goal?state.goal.toLocaleString('pt-BR',{minimumFractionDigits:2}):''}"></div><button class="primary" id="continue">Começar meu planejamento <span>→</span></button><small class="secure">♢ Seus dados ficam seguros e privados</small></section><aside class="quote"><p>“Um objetivo sem um plano é apenas um desejo.”</p><span>— Antoine de Saint-Exupéry</span></aside></main>`;const input=document.querySelector('#goal');input.addEventListener('input',()=>{const n=parseMoney(input.value);input.value=n?n.toLocaleString('pt-BR',{minimumFractionDigits:2}):''});document.querySelector('#continue').addEventListener('click',()=>{state.goal=parseMoney(input.value);if(!state.goal){input.focus();input.parentElement.classList.add('error');return}localStorage.setItem('xfinance-goal',state.goal);location.hash='carteira';render()})}
function portfolioPage(){if(!state.goal)return goalPage();const total=Object.values(state.values).reduce((a,b)=>a+Number(b),0),pct=Math.min(100,Math.round(total/state.goal*100)),starCount=pct>=100?5:pct>=75?4:pct>=50?3:pct>=25?2:pct>=10?1:0;let last='';const cards=investments.map((item,index)=>{const title=item[0]!==last?`<div class="category"><span class="cat-icon" style="--color:${item[2]}">${icons[item[1]]}</span><div><small>CATEGORIA</small><h3>${item[0]}</h3></div></div>`:'';last=item[0];return `${title}<article class="asset"><div class="asset-copy"><h4>${item[3]}</h4><p>${item[4]}</p></div><div class="asset-input"><label>SEU APORTE</label><div><span>R$</span><input data-id="${index}" inputmode="numeric" placeholder="0" value="${state.values[index]||''}"></div></div></article>`}).join('');document.querySelector('#app').innerHTML=`${header(2)}<main class="dashboard"><section class="builder"><div class="back" id="back">← <span>Voltar ao objetivo</span></div><h1>Monte sua <em>carteira</em></h1><p>Distribua seus aportes entre os investimentos. Sua carteira se atualiza em tempo real.</p>${cards}</section><aside class="side"><section class="summary"><div class="summary-head"><div><small>TOTAL INVESTIDO</small><strong>${money(total)}</strong></div><span>${pct}%</span></div><div class="chart-wrap"><div class="donut" style="--pct:${pct*3.6}deg"><div><b>${pct}%</b><small>do objetivo</small></div></div></div><div class="progress-label"><span>Progresso</span><b>${money(state.goal)}</b></div><div class="bar"><i style="width:${pct}%"></i></div><div class="stars">${[1,2,3,4,5].map(n=>`<span class="${n<=starCount?'won':''}">★</span>`).join('')}</div><p class="next">${starCount===5?'Objetivo alcançado! Você conseguiu.':'Próxima estrela ao avançar no seu objetivo'}</p></section><section class="community"><div class="community-title"><div><small>COMUNIDADE</small><h3>Quem você segue</h3></div><span>Ver todos →</span></div>${[['LM','Investidor #1842','78','4'],['RS','Investidora #0927','52','3'],['AC','Investidor #3104','31','2']].map(p=>`<div class="person"><div class="person-avatar">${p[0]}</div><div><b>${p[1]}</b><span>${'★'.repeat(+p[3])}<i>${'★'.repeat(5-p[3])}</i></span></div><strong>${p[2]}%</strong></div>`).join('')}<p>Perfis são anônimos para proteger a privacidade de todos.</p></section></aside></main>`;document.querySelector('#back').onclick=()=>{location.hash='';render()};document.querySelectorAll('.asset input').forEach(input=>input.addEventListener('change',()=>{state.values[input.dataset.id]=Number(input.value.replace(/\D/g,''));localStorage.setItem('xfinance-values',JSON.stringify(state.values));portfolioPage()}))}
function render(){location.hash==='#carteira'?portfolioPage():goalPage()}window.addEventListener('hashchange',render);render();
